version: '3'
services:
  nodejs:
    image: nodejs:1.0
    build:
          context: ./
          dockerfile: Dockerfile
    ports:
    - "3001:3000"
    - "3002:3000"
    links:
      - mongo
  mongo:
    image: mongo
