version: '3'
services:
  nginx:
    command: nginx -g "daemon off;"
    build: ./nginx-docker
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
  node1:
    build: .
    links:
        - mongo
        - redis
    ports:
        - "8080"
  node2:
    build: ./
    links:
        - mongo
        - redis
    ports:
        - "8080"
  node3:
    build: ./
    links:
        - mongo
        - redis
    ports:
        - "8080"
  mongo:
    image: mongo
  redis:
    image: redis
    ports:
        - "6379"
